apiVersion: v1
kind: ConfigMap
metadata:
  name: sonar-config
data:
  hudson.plugins.sonar.SonarGlobalConfiguration.xml: |
    <?xml version='1.1' encoding='UTF-8'?>
    <hudson.plugins.sonar.SonarGlobalConfiguration plugin="sonar@2.9">
        <installations>
            <hudson.plugins.sonar.SonarInstallation>
                <name>SonarQube1</name>
                <serverUrl>http://sonarqube.server</serverUrl>
                <credentialsId></credentialsId>
                <mojoVersion></mojoVersion>
                <additionalProperties></additionalProperties>
                <additionalAnalysisProperties></additionalAnalysisProperties>
                <triggers>
                    <skipScmCause>false</skipScmCause>
                    <skipUpstreamCause>false</skipUpstreamCause>
                    <envVar></envVar>
                </triggers>
            </hudson.plugins.sonar.SonarInstallation>
        </installations>
        <buildWrapperEnabled>true</buildWrapperEnabled>
        <dataMigrated>true</dataMigrated>
        <credentialsMigrated>true</credentialsMigrated>
    </hudson.plugins.sonar.SonarGlobalConfiguration>
  org.quality.gates.jenkins.plugin.GlobalConfig.xml: |
    <?xml version='1.1' encoding='UTF-8'?>
    <org.quality.gates.jenkins.plugin.GlobalConfig plugin="sonar-quality-gates@1.3.1">
        <listOfGlobalConfigData>
            <org.quality.gates.jenkins.plugin.GlobalConfigDataForSonarInstance>
                <name>sonartest</name>
                <username>admin</username>
                <sonarUrl>http://sonar-server</sonarUrl>
                <secretPass>{AQAAABAAAAAQQP4oX6TnCSqHdppEB/AecCPLUQVSsHX221jbs8X8n0g=}</secretPass>
                <timeToWait>0</timeToWait>
                <maxWaitTime>0</maxWaitTime>
            </org.quality.gates.jenkins.plugin.GlobalConfigDataForSonarInstance>
        </listOfGlobalConfigData>
        <globalConfigurationService>
            <listOfGlobalConfigInstances reference="../../listOfGlobalConfigData"/>
        </globalConfigurationService>
    </org.quality.gates.jenkins.plugin.GlobalConfig>