apiVersion: v1
kind: Route
metadata:
  name: report-nginx
spec:
  to:
    kind: Service
    name: report-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: "report-nginx"
spec:
  selector:
    app: "report-nginx"
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
kind: DeploymentConfig
apiVersion: "v1"
metadata:
  labels:
    app: "report-nginx"
  name: "report-nginx"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "report-nginx"
    spec:
      containers:
      - name: "report-nginx"
        image: " "
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  triggers:
    - type: "ConfigChange"
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "report-nginx"
        from:
          kind: "ImageStreamTag"
          name: "nginx:latest"
          namespace: "openshift"