apiVersion: v1
kind: Route
metadata:
  name: report-nginx
spec:
  to:
    kind: Service
    name: report-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: "report-nginx"
spec:
  selector:
    app: "report-nginx"
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-nginx
  labels:
    app: report-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-nginx
  template:
    metadata:
      labels:
        app: report-nginx
    spec:
      containers:
      - name: report-nginx
        image: docker.io/dimssss/nginx-for-ocp:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: report-kbit-tests
          mountPath: /opt/app-root/src
      volumes:
        - name: report-kbit-tests
          configMap:
            name: report-kbit-tests

